config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    resources :comments, except: [:index, :new, :show] do
      member do
        get :reply
      end
    end
  end
  devise_for :users

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can [:edit, :update, :destroy], Comment, user_id: user.id
    can [ :read, :show, :create, :reply], Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true, length: { maximum: 255 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable
  before_action :set_comment, only: [ :reply, :edit, :update, :destroy ]
  load_and_authorize_resource :comment, param_method: :comment_params

  def reply
    @reply = @commentable.comments.build(parent: @comment)
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        BroadcastCommentJob.perform_now @comment, 'create'
        format.html { redirect_to @commentable, notice: "Comment was successfully created."}
        format.json { render json: @comment }
        format.js
      else
        format.html { render :back, notice: "Comment was not created." }
        format.json { render json: @comment.errors }
        format.js
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        BroadcastCommentJob.perform_now @comment, 'update'
        format.html { redirect_to @commentable, notice: "Comment was successfully updated."}
        format.json { render json: @comment }
        format.js
      else
        format.html { render :back, notice: "Comment was not updated." }
        format.json { render json: @comment.errors }
        format.js
      end
    end
  end

  def destroy
    old_comment = @comment.dup
    old_comment.id = @comment.id
    @comment.destroy if @comment.errors.empty?
    BroadcastCommentJob.perform_now old_comment, 'destroy'
    respond_to do |format|
      format.html { redirect_to @commentable, notice: "Comments was successfully destroyed."}
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def set_comment
    begin
      @comment = @commentable.comments.find(params[:id])
    rescue => e
      logger.error "#{e.class.name} : #{e.message}"
      @comment = @commentable.comments.build
      @comment.errors.add(:base, :recordnotfound, message: "That record doesn't exist. Maybe, it is already destroyed.")
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order( created_at: :desc )
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>" class="comment" data-channel="comment-<%= comment.id %>" data-user-id="<%= comment.user.id %>">
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <div class="comment-info">
    <small>-
      <%= comment.user.name %>
      <span class='dot-bullet'><%= localize(comment.created_at, format: :long) %></span>
      <% if comment.replies.size.zero? %>
        <% if broadcasted %>
          <span class='dot-bullet'><%= link_to "Edit", edit_polymorphic_path([comment.commentable, comment]), class: 'edit-comment-link', remote: true  %></span>
          <span class='dot-bullet'><%= link_to "Destroy", [comment.commentable, comment], method: :delete, class: 'delete-comment-link', data:{confirm:"Are your sure?"}, remote: true %></span>
        <% else %>
          <% if can? :update, comment %>
            <span class='dot-bullet'><%= link_to "Edit", edit_polymorphic_path([comment.commentable, comment]), class: 'edit-comment-link', remote: true  %></span>
          <% end %>
          <% if can? :destroy, comment %>
            <span class='dot-bullet'><%= link_to "Destroy", [comment.commentable, comment], method: :delete, class: 'delete-comment-link', data:{confirm:"Are your sure?"}, remote: true %></span>
          <% end %>
        <% end %>
      <% else %>  
        <!-- Note: very tricky !!!-->
        <%= link_to "For reply link", [comment.commentable, comment], method: :delete, class: 'delete-comment-link d-none' %>     
      <% end %>
      <span class='dot-bullet'><%= link_to "Reply", polymorphic_path([:reply, comment.commentable, comment]), class: 'reply-comment-link', remote: true  %></span>
      <% if broadcasted %>
        <span class='dot-bullet text-success'><%= "broadcasted...." %></span>
      <% else %>
        <span class='dot-bullet text-primary'><%= "page-loaded...." %></span>
      <% end %>
    </small>
  </div>
  <% if comment.replies.any? %>
    <ul>
      <%= render comment.replies, broadcasted: false %>
    </ul>
  <% end %>
</li>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= simple_form_for [comment.commentable, comment], remote: true do | f | %>
    <%= f.hidden_field :parent_id %>
    <%= f.input :content, label: false, placeholder: (f.object.parent_id.nil? ? 'Share your idea.' : 'Leave your reply.'), wrapper_html: { class: 'mb-1' }, input_html: { rows: 5, data:{ 'comment-id': (comment.persisted? ? comment.id : 'new') }} %>
    <span id="comment_<%= comment.persisted? ? comment.id : 'new' %>_chars_counter" class="comment_chars_counter">Remaining : 255</span>
    <div class='float-right'>
      <%= f.submit class: 'btn btn-primary btn-sm float-xs-right' %>
      <%= link_to "Cancel", "#", 'data-reply': comment.parent_id.present?, class: 'cancel-comment-link btn btn-primary btn-sm float-xs-right ml-1' if comment.persisted? or comment.parent %>
    </div>  
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/comments/_widget.html.erb
<div id="comments-widget-of-commentable-<%= commentable.id %>" class="comments-widget">
  <h2 class="comments-header">
    Comments <small id="comments-count-of-commentable-<%= commentable.id %>"><%= commentable.comments.size %></small>
  </h2>
  <ul class="comments-list" data-channel='comments' data-commentable-id="<%= commentable.id %>">
    <%= render commentable.comments.includes(:user, :replies, :commentable).where(parent: nil), broadcasted: false %>
  </ul>
  <!-- comment-form -->
  <%= render "comments/form", comment: commentable.comments.build  %>
</div>

app/views/comments/create.js.erb
// create.js.erb (CommentsController#create)
<% if @comment.parent %>
  $comment_parent = $("#comment_<%= @comment.parent.id %> > ul");
  if(!$comment_parent.length){
    $("#comment_<%= @comment.parent.id %>").append("<ul></ul>");
    $comment_parent = $("#comment_<%= @comment.parent.id %> > ul");
  }
  $comment_form = $("#comment_<%= @comment.parent.id %> .comment-form form");
<% else %>
  $comment_parent = $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-list");
  $comment_form = $("#comments-widget-of-commentable-<%= @commentable.id %> .comment-form form");
<% end %>

$comments_count = $("#comments-count-of-commentable-<%= @commentable.id %>");

<% if @comment.errors.empty?  # if no erros on creating a comment... %>
  $comments_count.html("<%= @commentable.comments.size %>").effect('highlight',{}, 1000);
  // $comment_parent.append("<%#=j render @comment %>").find('li').last().effect("highlight", {}, 1000);
  $comment_form[0].reset();
  // when a reply was created
  <% if @comment.parent.present? %>
    $comment_form.remove();
    // console.log("start");
    $comment = $("#comment_<%= @comment.parent.id %>");
    // console.log("end");
    $restore_link = $comment.find('a.delete-comment-link')[0];
    $reply_link = $comment.find('a.reply-comment-link')[0];
    $reply_link.href = $restore_link.href + "/reply";
    // suggested by Aleksandr Balakiriev
    <%# if @comment.parent.replies.size == 1 %>
<!--      console.log(">>>>> first reply was created....");-->
<!--      $edit_link = $comment.find('a.edit-comment-link')[0];-->
<!--      $delete_link = $comment.find('a.delete-comment-link')[0];-->
<!--      $edit_link.parentNode.remove();-->
<!--      $delete_link.parentNode.remove();-->
    <%# end %>
  <% end %>
  $("#comment_new_chars_counter").html("Remaining : 255");
<% else # if some errors occurs on creating a comment... %>
  $comment_form.before("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").prev().delay(1500).slideUp();
<% end %>

app/views/comments/destroy.js.erb
$comments_count = $("#comments-count-of-commentable-<%= @commentable.id %>");
<% if @comment.errors.empty? %>
  <% if @comment.parent && can?(:update, @comment.parent) %>
    // added edit and destroy link
    $links = $("#comment_<%= @comment.id %> .dot-bullet a");
    $edit_link = $links[0];
    $delete_link = $links[1];
    $edit_link.href = "<%= edit_post_comment_url(@comment.parent.commentable, @comment.parent) %>"
    $delete_link.href = "<%= post_comment_url(@comment.parent.commentable, @comment.parent) %>"
    $new_edit_link = document.createElement('span');
    $new_edit_link.className= 'dot-bullet ml-1';
    $new_edit_link.appendChild($edit_link);
    $new_delete_link = document.createElement('span');
    $new_delete_link.className= 'dot-bullet ml-1';
    $new_delete_link.appendChild($delete_link);
    $("#comment_<%= @comment.parent.id %> .comment-info small .dot-bullet")[0].after($new_edit_link, $new_delete_link);
    console.log($edit_link);
    console.log($delete_link);
  <% end %>
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

app/views/comments/edit.js.erb
// edit.js.erb
<% if @comment.errors.empty? %>
  $("#comment_<%= @comment.id %> > .comment-info .edit-comment-link").removeAttr("href");
  $("#comment_<%= @comment.id %> > .comment-info").after("<%=j render('comments/form', comment: @comment) %>");
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

// On editing a comment, call to counter of comment.
$("#comment_<%= @comment.id %> form textarea").trigger('keyup');

app/views/comments/reply.js.erb
// reply.js.erb
<% if @comment.errors.empty? %>
  $("#comment_<%= @comment.id %> > .comment-info .reply-comment-link").removeAttr("href");
  $("#comment_<%= @comment.id %> > .comment-info").after("<%=j render('comments/form', comment: @reply) %>");
<% else %>
  $("#comments-widget-of-commentable-<%= @commentable.id %> .comments-header").after("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").next().delay(1500).slideUp('fast');
<% end %>

app/views/comments/update.js.erb
// update.js.erb (CommentsController#create)
$comment_form = $("#comment_<%= @comment.id %> .comment-form form");
$comment = $("#comment_<%= @comment.id %>");
<% if @comment.errors.empty?  # if no erros on creating a comment... %>
  $comment.html("<%=j render @comment, broadcasted: true %>").find('li').last().effect("highlight", {}, 1000);
  $comment_form[0].remove();
<% else # if some errors occurs on creating a comment... %>
  $comment_form.before("<div class='alert alert-warning alert-dismissible fade in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= @comment.errors.full_messages.join('') %></div>").prev().delay(1500).slideUp();
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RORLA-Blog</title>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'rorlab_logo.png' %>
    <% if user_signed_in? %> 
      <%= tag :meta, name: 'current-user', data: { id: current_user.id } %> 
    <% end %>
  </head>

  <body>
    <div class="container">
      <header class='row'>
        <%= render "shared/header" %>
      </header>
      <div id="trunk" class='row'>
        <main class='col-md-9'>
          <div id="flash_messages"><%= flash_messages(:close) %></div>
          <%= yield %>
        </main>
        <aside class='col-md-3'>
          <%= render "shared/sidebar" %>
        </aside>
      </div>
      <footer class='row'>
        <%= render 'shared/footer' %>
      </footer>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%#= f.association :user %>
    <%= f.input :title %>
    <%= f.input :content, input_html: { rows: 10 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-outline-primary' %>
    <%= link_to "Show", @post, class: 'btn btn-outline-primary' if @post.persisted? %>
    <%= link_to 'Back', root_path, class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="post_<%= post.id %>" class='post'>
  <div class='post_title'><%= post.title %></div>
  <small class='post_info'>- 
    <%= post.user.name %> &bull;
    <%= localize post.created_at, format: :long %> &bull;
    <% if post.comments.any? %>
      <%= t(:comment_count, count: post.comments.size) %> &bull;
    <% end %>
    <%= link_to "View", post %> &bull;
    <%= link_to "Edit", edit_post_path(post) %> &bull;
    <%= link_to "Destroy", post, method: :delete, data: { confirm: "Are you sure?" } %>
  </small>
  <div class='post_content'>
    <% if action_name == 'show' %>
      <%= simple_format post.content %>
    <% else %>
      <% if post.content.size > 300 %>
        <%= simple_format truncate(post.content, length: 300) %>
        <div class='text-xs-right'><small><%= link_to 'Read more', post %></small></div>
      <% else %>
        <%= simple_format post.content %>
      <% end %>
    <% end %>
  </div>
</div >

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div id="posts">
  <% if @posts.size.zero? %>
    <div class="no_posts">
      No posts have been published.
    </div>
  <% else %>
    <%= render @posts %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render @post %>

<div class="form-actions">
  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-outline-primary' %>
  <%= link_to 'Back', posts_path, class: 'btn btn-outline-primary' %>
</div>

<%= render "comments/widget", commentable: @post %>

app/views/shared/_footer.html.erb
<p>This is a footer partial</p>

app/views/shared/_header.html.erb
<h1>
  RORLA-Blog
</h1>

app/views/shared/_sidebar.html.erb
<% unless current_page?(root_path) %>
  <%= link_to 'Home', root_path, class: 'btn btn-outline-primary btn-block my-1' %>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-outline-primary btn-block my-1' %>
  <%= link_to "Profile", edit_user_registration_path, class: 'btn btn-outline-primary btn-block my-1' %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete, data: {confirm:"Are you sure?"}, class: 'btn btn-outline-primary btn-block my-1' %>
<% else %>
  <%= link_to "Log in", new_user_session_path, class: 'btn btn-outline-primary btn-block my-1' unless current_page?(new_user_session_path) %>
  <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-outline-primary btn-block' unless current_page?(new_user_registration_path) %>
<% end %>